services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=vicente.training.real-estate-executive.com
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - 3001:3001
      - 8000:8000
    networks:
      - app_network
    environment:
      - NODE_ENV=production
      - DB_HOST=db
  worker-cron:
    container_name: dapp-worker-cron
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    environment:
      DB_HOST: db
      NODE_ENV: production
    depends_on:
      - db
    networks:
      - app_network
  db:
    container_name: db
    image: postgres:15.7-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dapp_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    networks:
      - app_network

networks:
  app_network:
